language: minimal

services:
    - docker

before_install:
    - docker-compose up -d
    - tools/docker/waitForContainerSetup.sh

script:
    - docker-compose exec db env
    - docker-compose logs db
    - docker-compose exec db mysql -e 'SELECT NOW()'
