language: minimal

services:
    - docker

before_install:
    - docker-compose up -d
    - tools/docker/waitForContainerSetup.sh

script:
    - docker-compose exec db env
    - docker-compose logs --no-color db | sed 's/.*\[/[/'
    - docker-compose exec -eMYSQL_PWD=123456 db mysql -e 'SELECT NOW()'
