language: minimal

services:
    - docker

before_install:
    - docker-compose up -d
    - tools/docker/waitForContainerSetup.sh
    - docker-compose logs -f starter

script:
    - docker-compose exec -eMYSQL_PWD=123456 db mysql -e 'SELECT NOW()'
    - docker-compose exec back php -m
    - curl -vvv localhost
