language: minimal

services:
    - docker

before_install:
    - docker-compose up -d
    - tools/docker/waitForContainerSetup.sh
    - docker-compose logs -f starter mocha

script:
    - docker-compose run --rm mocha mocha-casperjs --timeout=360000 --bail

addons:
    hosts:
        - wpt.localhost
