dist: xenial

os: linux

language: shell

env:
  matrix:
#    - WP_VERSION=
    - WP_VERSION=5.1

services:
    - docker

before_install:
    - docker-compose build --build-arg DEVELOPER_ID=2000
    - docker-compose up -d
    - tools/docker/waitForContainerSetup.sh
    - docker-compose logs -f starter mocha

script:
    - docker-compose run --rm mocha mocha-casperjs --timeout=360000 --bail

addons:
    hosts:
        - wpt.localhost
